defaults: &defaults
  database:
    adapter: 'redis'
    host: 'localhost'
    port: '6379'

development:
  <<: *defaults
  database:
    db: '2'

test:
  <<: *defaults
  database:
    db: '3'

production:
  <<: *defaults
  database:
    db: '1'